name: frappe_docker
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: bind
        source: /mnt/c/Users/Qiany/erp/apps/
        target: /home/frappe/frappe-bench/apps/
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
  configurator:
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      redis-cache:
        condition: service_started
        required: true
      redis-queue:
        condition: service_started
        required: true
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: database-1.cxmio6kayuix.ca-central-1.rds.amazonaws.com
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: never
    restart: on-failure
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: bind
        source: /mnt/c/Users/Qiany/erp/apps/
        target: /home/frappe/frappe-bench/apps/
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
        required: true
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: uptrend
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: bind
        source: /mnt/c/Users/Qiany/erp/apps/
        target: /home/frappe/frappe-bench/apps/
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: bind
        source: /mnt/c/Users/Qiany/erp/apps/
        target: /home/frappe/frappe-bench/apps/
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: bind
        source: /mnt/c/Users/Qiany/erp/apps/
        target: /home/frappe/frappe-bench/apps/
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      default: null
    restart: unless-stopped
  redis-queue:
    image: redis:6.2-alpine
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}
  scheduler:
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: bind
        source: /mnt/c/Users/Qiany/erp/apps/
        target: /home/frappe/frappe-bench/apps/
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: custom:2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - logs:/home/frappe/frappe-bench/logs
      - type: volume
        source: assets
        target: /home/frappe/frappe-bench/sites/assets
        volume: {}
networks:
  default:
    name: frappe_docker_default
volumes:
  redis-queue-data:
    name: frappe_docker_redis-queue-data
  sites:
    name: frappe_docker_sites
  logs:
    name: frappe_docker_logs
  assets:
    name: frappe_docker_assets
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: custom:2
  pull_policy: never
  restart: unless-stopped
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - assets:/home/frappe/frappe-bench/sites/assets
x-customizable-image:
  image: custom:2
  pull_policy: never
  restart: unless-stopped
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
